### ISSUE TITLE
Start failure on IDA Python 3.12

### ISSUE THREAD

**Issue by MinatoTW** [mahaloz/decomp2dbg#95]
After installing via pip and selecting IDA pro, IDA pro crashes with "Error 1442" on opening. Problem is resolved after deleting decomp2dbg file and folder from plugins.

![image](https://github.com/mahaloz/decomp2dbg/assets/31851651/7f193190-9b19-4808-b6fc-e94426d45f4c)

Python version 3.12 on Arch Linux 64 bit.

**Comment by mahaloz** [comment]
And you're 100% d2d is the only culprit? I ran latest d2d on ida 8.4 for Mac and it worked great this weekend. 

I find it strange since the plugin, on load from ida, only makes a toolbar menu.

**Comment by MinatoTW** [comment]
Yes, I'm sure. It happened as soon as I installed the plugin and goes away when I delete it. Looked at the strings in the generated IDA dump and it had the d2d file path in it.

**Comment by mahaloz** [comment]
Alright, this one may take a while to close. I don't have access to a Linux copy of IDA Pro 8.4 yet, and I don't see any obvious bugs in our current implementation. Maybe 3.12 is a culprit here. Any chance you can execute your `idapyswitch` binary in your IDA install, switch to non-3.12, and report back if it still does this?

**Comment by MinatoTW** [comment]
Yup, it was 3.12, works with 3.10. Thank you, this plugin is amazing.

**Comment by MinatoTW** [comment]
Although, now after i connect with GDB (GEF) I get the error `[!] Command 'context' failed to execute properly, reason: 'NoneType' object has no attribute 'items'`.
It's able to resolve main but no pseudocode. I guess that's related to the python version too?

**Comment by MinatoTW** [comment]
Never mind, that had issues with decompilation due to a huge stack frame.

**Comment by k4lizen** [comment]
I can confirm that I also had the same issue. The binary was normal, IDA segfaults when run with python version 3.12 but works with 3.10.

**Comment by mahaloz** [comment]
@k4lizen, would you be able to attach the binary for testing?

**Comment by k4lizen** [comment]
yeah you can get it here: https://pwnable.tw/static/chall/babystack

**Comment by LittFlower** [comment]
I also encountered this problem :(

**Comment by mahaloz** [comment]
Hi @LittFlower can you provide your:
- OS
- Decompiler (and version)

And I assume this is Python 3.12 still right? 
Looking for any info I can reproduce on.

**Comment by LittFlower** [comment]
> Hi @LittFlower can you provide your:
> - OS
> - Decompiler (and version)
> 
> And I assume this is Python 3.12 still right? 
> Looking for any info I can reproduce on. 
Yes, I usually use arch linux python 13.0 as the runtime python of ida. However, when I open ida after installing the plug-in, the same error report as in this post will appear, IDA pro crashes with "Error 1442" on opening。 When I switched to 3.10.12 using idapyswitch, everything was normal, so I guess it's a problem with the Python version.

**Comment by mahaloz** [comment]
Ok, so the common trend is still `3.12` on Linux. I have access IDA 9 on Linux now, so I'll see if I can reproduce soon.

**Comment by mahaloz** [comment]
Update: This bug is very much real. I've triggered it on many systems... don't ask how. `libbs` is causing a segfault in Python 3.12 on Linux, IDA 9. It has something to do with Qt. Triaging this today. Wild bug.

**Comment by mahaloz** [comment]
Alright gang, that is wrap! You'll need to `pip install -U decomp2dbg`, and reinstall the files, and the crash should go away on 3.12 :)

**Comment by k4lizen** [comment]
Hahahahha holy three line fix. What was the issue?

**Comment by mahaloz** [comment]
@k4lizen it's a bug in how IDA handles classes that subclass two things at the same time (multiple inheritance). If one of those classes is a Qt class, it causes what looks like an out-of-bounds read in memory for the Python object (in C++). Did not dig deeper, since I figured out the mitigation.

**Comment by k4lizen** [comment]
awesome, thanks for the fix :>

**Comment by LittFlower** [comment]
yep... I can use this version on python3.13, thanks for the fix :)
